#!/bin/sh

pkgver=4.1
_wwwpkgver=4.1
source_core="https://github.com/pi-hole/pi-hole/archive/v$pkgver.tar.gz"
source_admin="https://github.com/pi-hole/AdminLTE/archive/v$_wwwpkgver.tar.gz"
dircorea="pi-hole-$pkgver"
dircoreb="$dircorea.cust"
diradmina="AdminLTE-$pkgver"
diradminb="$diradmina.cust"

_ssc="/tmp/sedcontrol"

[[ -d $dircorea ]] && rm -r $dircorea
[[ -d $dircoreb ]] && rm -r $dircoreb
[[ -d $diradmina ]] && rm -r $diradmina
[[ -d $diradminb ]] && rm -r $diradminb

wget -q -nc -O pihole-$pkgver.tar.gz $source_core
wget -q -nc -O admin-$_wwwpkgver.tar.gz $source_admin
tar xf pihole-$pkgver.tar.gz
tar xf admin-$_wwwpkgver.tar.gz
cp -a $dircorea $dircoreb
cp -a $diradmina $diradminb

# the return of service management
sed -i "s|service \${resolver} \${svcOption}|systemctl \${svcOption} \${resolver}|w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: the return of service management" && exit 1 ; fi

# setting up and securing pihole wrapper script
#sed -n "/debugFunc() {/w $_ssc" "$dircoreb"/pihole
#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 1" && exit 1 ; fi
#sed -i '/debugFunc() {/,+16d' "$dircoreb"/pihole

sed -n "/updatePiholeFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 2" && exit 1 ; fi
sed -i '/updatePiholeFunc() {/,+5d' "$dircoreb"/pihole

sed -n "/reconfigurePiholeFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 3" && exit 1 ; fi
sed -i '/reconfigurePiholeFunc() {/,+4d' "$dircoreb"/pihole

sed -n "/uninstallFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 4" && exit 1 ; fi
sed -i '/uninstallFunc() {/,+4d' "$dircoreb"/pihole

sed -n "/piholeCheckoutFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 5" && exit 1 ; fi
sed -i '/piholeCheckoutFunc() {/,+22d' "$dircoreb"/pihole

sed -n "/tricorderFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 6" && exit 1 ; fi
sed -i '/tricorderFunc() {/,+29d' "$dircoreb"/pihole

sed -n "/\"\-[r,up]/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 7" && exit 1 ; fi
sed -i '/\"\-[r,up]/d' "$dircoreb"/pihole

#sed -n "/^  \-d/w $_ssc" "$dircoreb"/pihole
#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 8" && exit 1 ; fi
#sed -i '/^  \-d/,+2d' "$dircoreb"/pihole

sed -n "/^  \-up/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 9" && exit 1 ; fi
sed -i '/^  \-up/d' "$dircoreb"/pihole

sed -n "/^  \-r/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 10" && exit 1 ; fi
sed -i '/^  \-r/d' "$dircoreb"/pihole

sed -n "/uninstall/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 11" && exit 1 ; fi
sed -i '/uninstall/d' "$dircoreb"/pihole

sed -i "s|^  checkout.*$|\";|w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 12" && exit 1 ; fi

sed -n "/checkout/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 13" && exit 1 ; fi
sed -i '/checkout/d' "$dircoreb"/pihole

sed -n "/tricorder/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 14" && exit 1 ; fi
sed -i '/tricorder/d' "$dircoreb"/pihole

# -----------------

# setup gravity.sh
sed -i "s|/usr/local/bin/|/usr/bin/|w $_ssc" "$dircoreb"/gravity.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 1" && exit 1 ; fi

# -----------------

# setting up and securing webpage.sh script
sed -i "s|/usr/local/bin/|/usr/bin/|w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 1" && exit 1 ; fi

# -----------------

# change log location to pihole script
sed -i "s|/var/log/pihole.log|/run/log/pihole/pihole.log|w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log location to pihole script" && exit 1 ; fi

# -----------------

# change log location to piholeLogFlush.sh
sed -n "/\/var\/log\/pihole.log/w $_ssc" "$dircoreb"/advanced/Scripts/piholeLogFlush.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log location to piholeLogFlush.sh" && exit 1 ; fi
sed -i "s|/var/log/pihole.log|/run/log/pihole/pihole.log|g" "$dircoreb"/advanced/Scripts/piholeLogFlush.sh

# -----------------

# change log and bin location to logrotate
sed -i "s|/var/log/pihole.log|/run/log/pihole/pihole.log|w $_ssc" "$dircoreb"/advanced/Templates/logrotate
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bin location to logrotate 1" && exit 1 ; fi
sed -i "s|/var/log/pihole-FTL.log|/run/log/pihole-ftl/pihole-FTL.log|w $_ssc" "$dircoreb"/advanced/Templates/logrotate
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bin location to logrotate 2" && exit 1 ; fi
sed -i "s|/usr/sbin|/usr/bin|w $_ssc" "$dircoreb"/advanced/Scripts/piholeLogFlush.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bin location to logrotate 3" && exit 1 ; fi

# -----------------

# change FTL port file location to chronometer.sh
sed -i "s|/var/run/pihole-FTL.port|/run/pihole-ftl/pihole-FTL.port|w $_ssc" "$dircoreb"/advanced/Scripts/chronometer.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change FTL port file location to chronometer.sh" && exit 1 ; fi

# -----------------

# no debug for us, right now
sed -n "/\-\- Generate debug log \-\-/w $_ssc" "$diradminb"/scripts/pi-hole/php/header.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: no debug for us, right now 1" && exit 1 ; fi
sed -i '/\-\- Generate debug log \-\-/,+5d' "$diradminb"/scripts/pi-hole/php/header.php

# -----------------

# change log location in admin php interface
#sed -i "s|/var/log/pihole.log|/run/log/pihole/pihole.log|w $_ssc" "$diradminb"/scripts/pi-hole/php/data.php
#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log location in admin php interface 1" && exit 1 ; fi

sed -i "s|/var/run/pihole-FTL.port|/run/pihole-ftl/pihole-FTL.port|w $_ssc" "$diradminb"/scripts/pi-hole/php/FTL.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log location in admin php interface 2" && exit 1 ; fi
sed -i "s|/var/log/pihole-FTL.log|/run/log/pihole-ftl/pihole-FTL.log|w $_ssc" "$diradminb"/scripts/pi-hole/php/tailLog.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log location in admin php interface 3" && exit 1 ; fi
sed -i "s|/var/log/pihole.log|/run/log/pihole/pihole.log|w $_ssc" "$diradminb"/scripts/pi-hole/php/tailLog.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log location in admin php interface 4" && exit 1 ; fi

# -----------------

# since we don't directly install from git...
#  sed -n "/\$core_branch =.*$/w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
#  if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't directly install from git... 1" && exit 1 ; fi
#  sed -i 's/\$core_branch =.*$/\$core_branch = "master";/' "$diradminb"/scripts/pi-hole/php/update_checker.php
#  sed -n "/\$web_branch =.*$/w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
#  if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't directly install from git... 2" && exit 1 ; fi
#  sed -i 's/\$web_branch =.*$/\$web_branch = "master";/' "$diradminb"/scripts/pi-hole/php/update_checker.php

sed -n "/\$core_current =.*$/w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't directly install from git... 3" && exit 1 ; fi
sed -i 's/\$core_current =.*$/\$core_current = "'"$pkgver"'";/' "$diradminb"/scripts/pi-hole/php/update_checker.php
sed -n "/\$web_current =.*$/w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't directly install from git... 4" && exit 1 ; fi
sed -i 's/\$web_current =.*$/\$web_current = "'"$_wwwpkgver"'";/' "$diradminb"/scripts/pi-hole/php/update_checker.php
sed -n "/\$FTL_current =.*$/w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't directly install from git... 5" && exit 1 ; fi
sed -i 's/\$FTL_current =.*$/\$FTL_current = exec("pihole-FTL version");/' "$diradminb"/scripts/pi-hole/php/update_checker.php

#  sed -n "/\$core_commit =.*$/w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
#  if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't directly install from git... 6" && exit 1 ; fi
#  sed -i 's/\$core_commit =.*$/\$core_commit = NULL;/' "$diradminb"/scripts/pi-hole/php/update_checker.php
#  sed -n "/\$web_commit =.*$/w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
#  if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't directly install from git... 7" && exit 1 ; fi
#  sed -i 's/\$web_commit =.*$/\$web_commit = NULL;/' "$diradminb"/scripts/pi-hole/php/update_checker.php

sed -i "s|/var/www/html/admin/|/srv/http/pihole/admin/|w $_ssc" "$dircoreb"/advanced/Scripts/version.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't directly install from git... 8" && exit 1 ; fi

#cd "$srcdir"/"$_pkgname"-"$pkgver"
#patch -p1 -i "$srcdir"/version.patch
#cd "$srcdir"

#sed -n "/{{corever}}/w $_ssc" "$dircoreb"/advanced/Scripts/version.sh
#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't directly install from git... 9" && exit 1 ; fi
#sed -i "s/{{corever}}/$pkgver/" "$dircoreb"/advanced/Scripts/version.sh
#sed -n "/{{webver}}/w $_ssc" "$dircoreb"/advanced/Scripts/version.sh
#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't directly install from git... 10" && exit 1 ; fi
#sed -i "s/{{webver}}/$_wwwpkgver/" "$dircoreb"/advanced/Scripts/version.sh

# -----------------

# web admin footer update setup
sed -i "s|https:\/\/github.com\/pi-hole\/pi-hole\/releases|https:\/\/aur.archlinux.org\/packages\/pi-hole-server|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 1" && exit 1 ; fi
sed -i "s|https:\/\/github.com\/pi-hole\/AdminLTE\/releases|https:\/\/aur.archlinux.org\/packages\/pi-hole-server|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 2" && exit 1 ; fi
sed -i "s|https:\/\/github.com\/pi-hole\/FTL\/releases|https:\/\/aur.archlinux.org\/packages\/pi-hole-server|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 3" && exit 1 ; fi

# -----------------

# sudo pihole full path (php-fpm compatibility)
sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/api.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 1" && exit 1 ; fi
sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/header.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 2" && exit 1 ; fi
sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/queryads.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 3" && exit 1 ; fi
sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/savesettings.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 4" && exit 1 ; fi
sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/sub.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 5" && exit 1 ; fi
sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/add.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 6" && exit 1 ; fi
sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/gravity.sh.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 7" && exit 1 ; fi
sed -i "s|sudo pihole|sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/loginpage.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 8" && exit 1 ; fi

# -----------------

# pi-hole sudoers file is now populated by install script
echo "http ALL=NOPASSWD: /usr/bin/pihole" >> "$dircoreb"/advanced/Templates/pihole.sudo

# pi-hole dnsmasq config file include ready
echo "conf-dir=/etc/dnsmasq.d/,*.conf" >> "$dircoreb"/advanced/dnsmasq.conf.original

# adlists.default is gone and adlists.list is populated by install script
# from basic-install.sh -- function chooseBlocklists()
cat <<EOF > "$dircoreb"/adlists.list
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
http://sysctl.org/cameleon/hosts
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://hosts-file.net/ad_servers.txt
EOF

diff -uprN $dircorea $dircoreb > arch-server-core-$pkgver.patch
diff -uprN $diradmina $diradminb > arch-server-admin-$pkgver.patch

git add arch-server-core-$pkgver.patch
git add arch-server-admin-$pkgver.patch

