#!/bin/sh

_pkgver=5.9
_wwwpkgver=5.11
source_core="https://github.com/pi-hole/pi-hole/archive/v$_pkgver.tar.gz"
source_admin="https://github.com/pi-hole/AdminLTE/archive/v$_wwwpkgver.tar.gz"
dircorea="pi-hole-$_pkgver"
dircoreb="$dircorea.cust"
diradmina="AdminLTE-$_wwwpkgver"
diradminb="$diradmina.cust"

_ssc="/tmp/sedcontrol"

[[ -d $dircorea ]] && rm -r $dircorea
[[ -d $dircoreb ]] && rm -r $dircoreb
[[ -d $diradmina ]] && rm -r $diradmina
[[ -d $diradminb ]] && rm -r $diradminb

wget -q -nc -O pihole-$_pkgver.tar.gz $source_core
wget -q -nc -O admin-$_wwwpkgver.tar.gz $source_admin
tar xf pihole-$_pkgver.tar.gz
tar xf admin-$_wwwpkgver.tar.gz
cp -a $dircorea $dircoreb
cp -a $diradmina $diradminb

# ================
# version.sh patch
# ================
cp -a version.patch version-${_pkgver}.patch
sed -i "s|{{_pkgver}}|v${_pkgver}|w $_ssc" ./version-${_pkgver}.patch
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: version.sh patch 1" && exit 1 ; fi
sed -i "s|{{_wwwpkgver}}|v${_wwwpkgver}|w $_ssc" ./version-${_pkgver}.patch
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: version.sh patch 2" && exit 1 ; fi
cd "$dircoreb"
patch -p1 -i ../version-${_pkgver}.patch
cd ..
rm version-${_pkgver}.patch
# ================
# version.sh patch
# ================

# the return of service management
sed -i "s|service pihole-FTL restart|systemctl restart pihole-FTL|w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: the return of service management" && exit 1 ; fi

# setting up and securing pihole wrapper script
#sed -n "/debugFunc() {/w $_ssc" "$dircoreb"/pihole
#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 1" && exit 1 ; fi
#sed -i '/debugFunc() {/,+16d' "$dircoreb"/pihole

sed -n "/updatePiholeFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 2" && exit 1 ; fi
sed -i '/updatePiholeFunc() {/,+5d' "$dircoreb"/pihole

sed -n "/reconfigurePiholeFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 3" && exit 1 ; fi
sed -i '/reconfigurePiholeFunc() {/,+4d' "$dircoreb"/pihole

sed -n "/uninstallFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 4" && exit 1 ; fi
sed -i '/uninstallFunc() {/,+4d' "$dircoreb"/pihole

sed -n "/piholeCheckoutFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 5" && exit 1 ; fi
sed -i '/piholeCheckoutFunc() {/,+22d' "$dircoreb"/pihole

sed -n "/tricorderFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 6" && exit 1 ; fi
sed -i '/tricorderFunc() {/,+20d' "$dircoreb"/pihole

sed -n "/\"\-[r,up]/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 7" && exit 1 ; fi
sed -i '/\"\-[r,up]/d' "$dircoreb"/pihole

#sed -n "/^  \-d/w $_ssc" "$dircoreb"/pihole
#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 8" && exit 1 ; fi
#sed -i '/^  \-d/,+2d' "$dircoreb"/pihole

sed -n "/^  \-up/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 9" && exit 1 ; fi
sed -i '/^  \-up/d' "$dircoreb"/pihole

sed -n "/^  \-r/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 10" && exit 1 ; fi
sed -i '/^  \-r/d' "$dircoreb"/pihole

sed -n "/uninstall/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 11" && exit 1 ; fi
sed -i '/uninstall/d' "$dircoreb"/pihole

sed -n "/^  checkout/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 12" && exit 1 ; fi
sed -i '/^  checkout/,+1d' "$dircoreb"/pihole

sed -n "/^  \"checkout/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 13" && exit 1 ; fi
sed -i '/^  \"checkout/d' "$dircoreb"/pihole

sed -n "/tricorder/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 14" && exit 1 ; fi
sed -i '/tricorder/d' "$dircoreb"/pihole

# -----------------

# setup gravity.sh
sed -i "s|/usr/local/bin/|/usr/bin/|w $_ssc" "$dircoreb"/gravity.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 1" && exit 1 ; fi
sed -i "s|source \"/etc/.pihole/advanced/Scripts/database_migration/gravity-db.sh\"|source \"/opt/pihole/database_migration/gravity-db.sh\"|w $_ssc" "$dircoreb"/gravity.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 2" && exit 1 ; fi
sed -i "s|\${piholeGitDir}/advanced/Templates/gravity|/opt/pihole/gravity|w $_ssc" "$dircoreb"/gravity.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 3" && exit 1 ; fi

# setup gravity.db.sh
sed -i "s|/etc/.pihole/advanced/Scripts/database_migration/gravity|/opt/pihole/database_migration/gravity|w $_ssc" "$dircoreb"/advanced/Scripts/database_migration/gravity-db.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 1" && exit 1 ; fi

# setup pihole
sed -i "s|/usr/local/bin|/usr/bin|w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup pihole 1" && exit 1 ; fi
sed -i "s|/run/pihole-FTL.pid|/run/pihole-ftl/pihole-FTL.pid|w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup pihole 2" && exit 1 ; fi

# -----------------

# setting up and securing pihole-reenable.sh script
sed -i "s|/usr/local/bin|/usr/bin|w $_ssc" "$dircoreb"/advanced/Scripts/pihole-reenable.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole-reenable.sh script 1" && exit 1 ; fi

# -----------------

# change log location to pihole script
sed -i "s|/var/log/pihole.log|/run/log/pihole/pihole.log|w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log location to pihole script" && exit 1 ; fi

# -----------------

# change log location to piholeLogFlush.sh
sed -n "/\/var\/log\/pihole.log/w $_ssc" "$dircoreb"/advanced/Scripts/piholeLogFlush.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log location to piholeLogFlush.sh" && exit 1 ; fi
sed -i "s|/var/log/pihole.log|/run/log/pihole/pihole.log|g" "$dircoreb"/advanced/Scripts/piholeLogFlush.sh

# -----------------

# change log and bin location to logrotate
sed -i "s|/var/log/pihole.log|/run/log/pihole/pihole.log|w $_ssc" "$dircoreb"/advanced/Templates/logrotate
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bin location to logrotate 1" && exit 1 ; fi
sed -i "s|/var/log/pihole-FTL.log|/run/log/pihole-ftl/pihole-FTL.log|w $_ssc" "$dircoreb"/advanced/Templates/logrotate
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bin location to logrotate 2" && exit 1 ; fi
sed -i "s|/usr/sbin|/usr/bin|w $_ssc" "$dircoreb"/advanced/Scripts/piholeLogFlush.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bin location to logrotate 3" && exit 1 ; fi
sed -i "s|/var/lib/logrotate/pihole|/var/lib/logrotate_pihole.status|w $_ssc" "$dircoreb"/advanced/Scripts/piholeLogFlush.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bin location to logrotate 3" && exit 1 ; fi

# -----------------

# chronometer and co. setup
sed -i "s|\${PI_HOLE_FILES_DIR}/automated install/basic-install.sh|/opt/pihole/basic-install.sh|w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: chronometer and co. setup 1" && exit 1 ; fi
sed -i "s|/run/pihole-FTL.port|/run/pihole-ftl/pihole-FTL.port|w $_ssc" "$dircoreb"/advanced/Scripts/chronometer.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: chronometer and co. setup 2" && exit 1 ; fi

# -----------------

# no debug for us, right now
sed -n "/\-\- Generate debug log \-\-/w $_ssc" "$diradminb"/scripts/pi-hole/php/header.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: no debug for us, right now 1" && exit 1 ; fi
sed -i '/\-\- Generate debug log \-\-/,+5d' "$diradminb"/scripts/pi-hole/php/header.php

# -----------------

# change log location in admin php interface
sed -i "s|/var/log/pihole-FTL.log|/run/log/pihole-ftl/pihole-FTL.log|w $_ssc" "$diradminb"/scripts/pi-hole/php/tailLog.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log location in admin php interface 1" && exit 1 ; fi
sed -i "s|/var/log/pihole.log|/run/log/pihole/pihole.log|w $_ssc" "$diradminb"/scripts/pi-hole/php/tailLog.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log location in admin php interface 2" && exit 1 ; fi

# -----------------

sed -n "/\$core_current =.*$/w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't directly install from git... 1" && exit 1 ; fi
sed -i 's/\$core_current =.*$/\$core_current = "'"$_pkgver"'";/' "$diradminb"/scripts/pi-hole/php/update_checker.php
sed -n "/\$web_current =.*$/w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't directly install from git... 2" && exit 1 ; fi
sed -i 's/\$web_current =.*$/\$web_current = "'"$_wwwpkgver"'";/' "$diradminb"/scripts/pi-hole/php/update_checker.php
sed -n "/\$FTL_current =.*$/w $_ssc" "$diradminb"/scripts/pi-hole/php/update_checker.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't directly install from git... 3" && exit 1 ; fi
sed -i 's/\$FTL_current =.*$/\$FTL_current = exec("pihole-FTL version");/' "$diradminb"/scripts/pi-hole/php/update_checker.php

#sed -i "s|/var/www/html/admin/|/srv/http/pihole/admin/|w $_ssc" "$dircoreb"/advanced/Scripts/version.sh
#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: since we don't directly install from git... 4" && exit 1 ; fi

# -----------------

# web admin footer update setup
sed -i "s|\$coreUrl\ \.\ \"\/releases\"\;|\"https:\/\/aur.archlinux.org\/packages\/pi-hole-server\";|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 1" && exit 1 ; fi
sed -i "s|\$webUrl\ \.\ \"\/releases\"\;|\"https:\/\/aur.archlinux.org\/packages\/pi-hole-server\";|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 2" && exit 1 ; fi
sed -i "s|\$ftlUrl\ \.\ \"\/releases\"\;|\"https:\/\/aur.archlinux.org\/packages\/pi-hole-ftl\";|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 3" && exit 1 ; fi

sed -i "s|\$coreReleasesUrl . \"/\" . \$core_current;|\$coreReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 4" && exit 1 ; fi
sed -i "s|\$webReleasesUrl . \"/\" . \$web_current;|\$webReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 5" && exit 1 ; fi
sed -i "s|\$ftlReleasesUrl . \"/\" . \$FTL_current;|\$ftlReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 6" && exit 1 ; fi

sed -i "s|\$coreReleasesUrl . \"/latest\";|\$coreReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 7" && exit 1 ; fi
sed -i "s|\$webReleasesUrl . \"/latest\";|\$webReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 8" && exit 1 ; fi
sed -i "s|\$ftlReleasesUrl . \"/latest\";|\$ftlReleasesUrl;|w $_ssc" "$diradminb"/scripts/pi-hole/php/footer.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 9" && exit 1 ; fi

# -----------------

# sudo pihole full path (php-fpm compatibility)
sed -i "s|\"sudo pihole \"|\"sudo /usr/bin/pihole \"|w $_ssc" "$diradminb"/scripts/pi-hole/php/func.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 1" && exit 1 ; fi
sed -i "s|\"sudo pihole|\"sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/queryads.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 2" && exit 1 ; fi
sed -i "s|'sudo pihole|'sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/savesettings.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 3" && exit 1 ; fi
sed -i "s|\"sudo pihole|\"sudo /usr/bin/pihole|w $_ssc" "$diradminb"/scripts/pi-hole/php/gravity.sh.php
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sudo pihole full path (php-fpm compatibility) 4" && exit 1 ; fi

# -----------------

# pi-hole sudoers file is now populated by install script
echo "http ALL=NOPASSWD: /usr/bin/pihole" >> "$dircoreb"/advanced/Templates/pihole.sudo

# pi-hole dnsmasq config file include ready
echo "conf-dir=/etc/dnsmasq.d/,*.conf" >> "$dircoreb"/advanced/dnsmasq.conf.original

# adlists.default is gone and adlists.list is populated by install script
# from basic-install.sh -- function chooseBlocklists()
cat <<EOF > "$dircoreb"/adlists.list
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
EOF

cat <<EOF > "$dircoreb"/dns-servers.conf
Google (ECS);8.8.8.8;8.8.4.4;2001:4860:4860:0:0:0:0:8888;2001:4860:4860:0:0:0:0:8844
OpenDNS (ECS, DNSSEC);208.67.222.222;208.67.220.220;2620:119:35::35;2620:119:53::53
Level3;4.2.2.1;4.2.2.2;;
Comodo;8.26.56.26;8.20.247.20;;
DNS.WATCH;84.200.69.80;84.200.70.40;2001:1608:10:25:0:0:1c04:b12f;2001:1608:10:25:0:0:9249:d69b
Quad9 (filtered, DNSSEC);9.9.9.9;149.112.112.112;2620:fe::fe;2620:fe::9
Quad9 (unfiltered, no DNSSEC);9.9.9.10;149.112.112.10;2620:fe::10;2620:fe::fe:10
Quad9 (filtered + ECS);9.9.9.11;149.112.112.11;2620:fe::11;2620:fe::fe:11
Cloudflare;1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001
EOF

diff -uprN $dircorea $dircoreb > arch-server-core-$_pkgver.patch
diff -uprN $diradmina $diradminb > arch-server-admin-$_wwwpkgver.patch

git add arch-server-core-$_pkgver.patch
git add arch-server-admin-$_wwwpkgver.patch
git add patchgen
